DROP TABLE IF EXISTS content_type CASCADE;
DROP TABLE IF EXISTS content_tag CASCADE;
DROP TABLE IF EXISTS content_permission CASCADE;
DROP TABLE IF EXISTS content_meta CASCADE;
DROP TABLE IF EXISTS content CASCADE;